// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRsgDLUcBD9UgKllH7dK1Syq5NoJlw2nQ',
    appId: '1:53220066521:web:c34923e88137f97470aac8',
    messagingSenderId: '53220066521',
    projectId: 'zlux-pos',
    authDomain: 'zlux-pos.firebaseapp.com',
    storageBucket: 'zlux-pos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHklUu33moug-COzUsoOv15ji_rohiI68',
    appId: '1:53220066521:android:9306e4182cf12b3570aac8',
    messagingSenderId: '53220066521',
    projectId: 'zlux-pos',
    storageBucket: 'zlux-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNldqYodzrUySaMMNIGiK9ECMCAXXKaNM',
    appId: '1:53220066521:ios:fb575af834cd5c5d70aac8',
    messagingSenderId: '53220066521',
    projectId: 'zlux-pos',
    storageBucket: 'zlux-pos.firebasestorage.app',
    iosBundleId: 'com.example.zluxPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNldqYodzrUySaMMNIGiK9ECMCAXXKaNM',
    appId: '1:53220066521:ios:fb575af834cd5c5d70aac8',
    messagingSenderId: '53220066521',
    projectId: 'zlux-pos',
    storageBucket: 'zlux-pos.firebasestorage.app',
    iosBundleId: 'com.example.zluxPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRsgDLUcBD9UgKllH7dK1Syq5NoJlw2nQ',
    appId: '1:53220066521:web:028386abf9fa73de70aac8',
    messagingSenderId: '53220066521',
    projectId: 'zlux-pos',
    authDomain: 'zlux-pos.firebaseapp.com',
    storageBucket: 'zlux-pos.firebasestorage.app',
  );
}
